version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: legallens-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3711157al
      POSTGRES_DB: legallens
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
