"""add file_path_and_size

Revision ID: 9d956d6c7e59
Revises: 8d138676f557
Create Date: 2025-08-02 21:39:25.438454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d956d6c7e59"
down_revision: Union[str, Sequence[str], None] = "8d138676f557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_path", sa.String(length=500), nullable=False)
    )
    op.add_column("documents", sa.Column("size_bytes", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "size_bytes")
    op.drop_column("documents", "file_path")
    # ### end Alembic commands ###
