"""analysis requests table

Revision ID: f172f0e5d46b
Revises: cf286c03c181
Create Date: 2025-08-07 19:57:52.320742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f172f0e5d46b"
down_revision: Union[str, Sequence[str], None] = "cf286c03c181"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("normalized", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_requests_document_id"),
        "analysis_requests",
        ["document_id"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_document_chunks_embedding"),
        table_name="document_chunks",
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_document_chunks_embedding"),
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_index(
        op.f("ix_analysis_requests_document_id"), table_name="analysis_requests"
    )
    op.drop_table("analysis_requests")
    # ### end Alembic commands ###
